[package]
name = "hello_client"
version = "0.1.0"
authors = ["Maciek Makowski <public@mmakowski.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.19"